---
title: "Individual project option 2: Rubric"
subtitle: "136 points possible"
format: html
---

# Data 200: Independent Project

## Introduction to the data: Employment

This data on employment comes from the California Open Data Portal <https://data.ca.gov/dataset/current-employment-statistics-ces-2/resource/98b69522-557e-464a-a2be-4226df433da1>. 

The Current Employment Statistics (CES) program is a Federal-State cooperative effort in which monthly surveys are conducted to provide estimates of employment, hours, and earnings based on payroll records of business establishments. 
The CES survey is based on approximately 119,000 businesses and government agencies representing approximately 629,000 individual worksites throughout the United States.

CES data reflect the number of nonfarm, payroll jobs. 
It includes the total number of persons on establishment payrolls, employed full- or part-time, who received pay (whether they worked or not) for any part of the pay period that includes the 12th day of the month. 
Temporary and intermittent employees are included, as are any employees who are on paid sick leave or on paid holiday. 
Persons on the payroll of more than one establishment are counted in each establishment. 
CES data excludes proprietors, self-employed, unpaid family or volunteer workers, farm workers, and household workers. 
Government employment covers only civilian employees; it excludes uniformed members of the armed services.

The Bureau of Labor Statistics (BLS) of the U.S. Department of Labor is responsible for the concepts, definitions, technical procedures, validation, and publication of the estimates that State workforce agencies prepare under agreement with BLS.

## Instructions

Essentially this project will require the same skills you have been learning in class and practicing in the labs and homework, but without the guard rails. I am not instructing you on what functions to use, just the tasks to accomplish.

Remember that you can use resources, but responsibly. If you ask a friend for help, make sure you two do not have identical responses. If you use the AI tools or Google searches for help, do not just copy code, make sure you understand what it is doing.

You'll write all of your code in the `individual-project.qmd` file in this repo.

### Data cleaning [62 points] 

- [4 points] Read in your data and clean the column names to comply with tidyverse style guide rules.
- [4 points] Identify number of rows and columns.
- [4 points] What does one observation represent?
- [8 points] Identify the type for each variable and if it has an appropriate R type.
- [4 points] Identify how many counties are in the data frame.
- [4 points] Convert the `date` column to be a date R type.
- [4 points] Our data will get too massive if we keep all of it. Filter to keep only dates equal to January 1 for the years 2021-2025.
- [8 points] Add a column called `county` which will store `NA` if the observation is not for a county, and will store the name of the county if the observation is for a county. 
- [4 points] We don't want each county name in our `county` variable to end in "County". Remove the word "County" from the new `county` variable you defined (i.e. "Ventura Conty" should be changed to just "Ventura").
- [4 points] Some of the capitalization differs for industry titles. Standardize the capitalization by making the values of `industry_title` use title case (i.e. Capitalize first letter of each word).
- [10 points] Your final task will be to create a map with our data. First we will need to include latitude and longitude for each county. The `map_data()` provides the necessary longitude and latitude data for different geographic regions, including California counties. Use `map_data("county", region = "california")` to load in the geographic data. Notice there is a mismatch between the county variables is your employment data and the geographic data. Identify and rectify the issue, then join the data frames, keeping only rows and columns present in both data frames.
- [4 points] Save the cleaned data frame into the `data` folder and name it `employment-data-cleaned.csv`

### Data summarizing [42 points]

- [8 points] Plot the distribution of current employment for all counties on January 1, 2024 (together, not separately).
- [8 points] Plot employment totals for Ventura County overtime for industry title "Total, All Industries".
- [8 points] Which California counties have the minimum and maximum employment total for  for industry title "Total, All Industries" for Janurary 1, 2024?
- [8 points] Challenge: Plot employment totals for industry title "Total, All Industries" by county on a map for 2024. Hint: You can use the following code to produce a map by county `ggplot(aes(x = long, y = lat, group = county, fill = current_employment)) + geom_polygon()`.
- [10 points] Finally, pose your own question and produce a visual to help answer it. Make sure the write out your question.

### Version control [10 points]

- [2 points for pushing] Make sure to commit and push fairly frequently, especially after you make a big change or take a break.
- [4 points for pushing] Part of your grade will be based on appropriate commit frequency (minimum 3 times).
- [4 points for pushing] Part of your grade will be based on clear and concise commit messages 

### Coding [20 points]

- [4 points] Follow tidyverse style guide.
- [4 points] When reporting calculations use inline R code instead of typing out a number.
- [12 points] For all plots specif: axes labels, plot titles, and alternate text.

### Resources used [2 points] 

- Have you done the project by yourself, with a peer(s), or used tools like ChatGPT? 
- If you provided help to a peer(s) and/or got help from your peers(s) please explain briefly what this entailed. 
- If you used tools like ChatGPT, include the prompts you used and explain how the tool helped supported your learning. 

