---
title: "Data 200: Lecture 13a"
subtitle: "Introduction to unsupervised learning: K-means clsutering"
author: "Professor Catalina Medina"
execute:
  echo: true
format: 
  revealjs:
    theme: [sky, ../slide-style.scss]
    slide-number: true
---

```{r}
#| echo: false
options(scipen = 0)
library(tidyverse)
library(openintro)
library(broom)
library(modelr)
theme_set(theme_bw(base_size = 22))
```

# Reviewing vocabulary

## Machine learning

**Machine learning** is a broad term for building models to analyze data, detect patterns, and make predictions.

- When you built linear or logistic regression models for prediction, that was machine learning
- *Linear regression was appropriate for what type of $Y$ variable?*
- *Logistic regression was appropriate for what type of $Y$ variable?*

## Variables

There are different ways people refer to the $X$ and $Y$ variables in regression:

| X | Y |
|:----------|:----------|
| Explanatory variable(s) | Response variable |
| Feature(s) | Target |
| Predictors | Outcome |
| Input | Output |


## Labeled data

When building predictive regression models we

1. Split the data into a training and a testing data set
2. Fit/estimated the model using the training data
3. Assess predictive performance using the testing data
  
. . .

We were working with **labeled data**, where we know the true target of interest $Y$ in our sample to train our model with

- This allowed us to compare true $Y$ values to predicted $Y$ values

## Supervised learning

**Supervised machine learning** is machine learning done with labeled data

Example motivation: 

- Training a model to predict heart disease by using past patient data for people with and without 
- Training a model to predict house sell price using recently sold housing data

Regression (linear and logistic) models are forms of supervised machine learning

## Unsupervised learning

**Unsupervised machine learning** is machine learning done with unlabeled data. 

- Aims to discover hidden patterns or relationships within the data without prior knowledge of the desired output (**unlabeled data**)

Examples: 

- Grouping genes with similar expression patterns to understand their functions
- Identifying the underlying themes or topics present in a collection of text documents, like news articles

## K-mean clustering

**K-means clustering** is an unsupervised machine learning method 

